[project]
name = "conda-metadata-api"
version = "0.1.0"
description = "Add a short description here"
authors = ["jaimergp <jaimergp@users.noreply.github.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
dev = "uvicorn main:app"

[dependencies]
fastapi = "0.100.1.*"
uvicorn = "0.23.1.*"
conda-forge-metadata = "0.5.0.*"
